log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

airdrop:
  amount: amount # amount in natural numbers (1, 2, 10 etc.) decimals part is taken directly from the contract
  token_address: erc20_token_address

broadcaster:
  rpc: evm_rpc_url
  chain_id: chain_id
  sender_private_key: priv_key
  query_limit: 10
  erc20_permit_transfer: contract_address
  gas_multiplier: 1.1

verifier:
  verification_key_path: "./verification_key.json"
  allowed_age: 18
  allowed_citizenships: [ "UKR" ]
  allowed_event_id: "event_id"
  allowed_query_selector: "query_selector"
  # at least one of these should be correct to pass:
  allowed_identity_count: 1
  allowed_identity_timestamp: 1715698750

root_verifier:
  rpc: evm_rpc_url
  contract: registration_contract_address
  request_timeout: 10s

price_api:
  url: api_url  #coinmarketcap
  key: api_key
  currency_id: 23888
  quote_tag: "ETH"