log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

airdrop:
  amount: amount
  token_address: erc20_token_address

broadcaster:
  rpc: evm_rpc_url
  chain_id: chain_id
  sender_private_key: priv_key
  query_limit: 10

verifier:
  verification_key_path: "./verification_key.json"
  allowed_age: 18
  allowed_citizenships: ["UKR"]
  allowed_event_id: "event_id"
  allowed_query_selector: "query_selector"
  # at least one of these should be correct to pass:
  allowed_identity_count: 1
  allowed_identity_timestamp: 1715698750

root_verifier:
  rpc: evm_rpc_url
  contract: registration_contract_address
  request_timeout: 10s
